### ISSUE TITLE
Error: Cannot find module '../build/Release/bson']

### ISSUE THREAD

**Issue by manuel-reil** [vbuzzano/sails-hook-jobs#9]
Might be an oldie, but on sails lift, I get the following error:

```
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```

I saw this: https://github.com/rschmukler/agenda/issues/200 but could not figure out a solution for me. 

Any workaround or fix?

Thank you,
Manuel

---

sails.js 0.12.3, 0.12.4
sails-mongo 0.12.1
npm 2.15.5

**Comment by vbuzzano** [comment]
This a problem with the Mongodb module.  it's work anyway.                                                                                                                                                                         Envoyé depuis BlackBerry Hub pour Android                                                                                                                                                                                                                   De:notifications@github.comEnvoyé:14 août 2016 3:14 PMÀ:sails-hook-jobs@noreply.github.comRépondre à:reply@reply.github.comObjet:[vbuzzano/sails-hook-jobs] Error: Cannot find module '../build/Release/bson'] (#9)  Might be an oldie, but on sails lift, I get the following error:

{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version

I saw this: rschmukler/agenda#200 but could not figure out a solution for me. 

Any workaround or fix?

Thank you,
Manuel

sails.js 0.12.3, 0.12.4
sails-mongo 0.12.1
npm 2.15.5

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
